language: go
sudo: false
osx_image: xcode7.3

os:
  - linux
  - osx

go:
  - 1.5.4
  - 1.6.2
  - tip

install:
 - go get -t ./...
 - go get -u github.com/kisielk/errcheck
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u github.com/golang/lint/golint

script:
  - make check
  - go test ./...
  - go test -cpu=2 -race ./...
